language: python
python:
  - "2.7"
  - "3.0"

branches:
 only:
  - master
addons:
  apt:
    packages:
      - devscriptssudo \
        falseFlask==0.10.1 \
        Flask-Bootstrap==3.3.2.1 \
        Flask-Script==2.0.5 \
        Jinja2==2.7.3 \
        MarkupSafe==0.23 \
        Werkzeug==0.10.4 \
        argparse==1.2.1 \
        distribute==0.6.24 \
        ipython==3.1.0 \
        itsdangerous==0.24 \
        netifaces==0.10.4 \
        python-consul==0.3.18 \
        requests==2.7.0 \
        six==1.9.0 \
        wsgiref==0.1.2:
        
      
notifications:
  email: false
  irc:
    on_success: change # no need for spam
    on_failure: always
    channels:
      - "irc.oftc.net#munin"
    template:
      - "%{repository} (%{branch} - %{commit} : %{author}): %{message}"
      - "Build details: %{build_url}"
matrix:
  # we don't need to continue any build when 1 test is failing.
  fast_finish: true

env:
  - TEST_MEDIUM=1
